url: https://luileechoi.github.io

# Site settings
title: Lee Choi Trading Company
email: luileechoi@gmail.com
description: "Your partner in trading non-ferrous metal, e-waste and plastic scrap."


# Team names, titles and social links
people:
- name: #
  pic: #
  position: CEO
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: stack-overflow
      url: #

- name: #
  pic: #
  position: Sales Manager 1
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #

- name: #
  pic: #
  position: Sales Manager 2
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: google-plus
      url: #

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: #
  - title: facebook
    url:
  - title: stack-overflow
    url: #
  - title: bitbucket 
    url: #
  - title: github
    url: #

# Postal address (add as many lines as necessary)
address:
  - line: Rm 1502 15/f City Landmark I
  - line: 68 Chung On St
  - line: Tsuen Wan
  - line: Hong Kong

# Build settings
markdown: kramdown
permalink: pretty
